checkInterval = "30s"
bscUrls = [
    "https://data-seed-prebsc-1-s1.binance.org:8545/",
    "https://data-seed-prebsc-2-s1.binance.org:8545/",
    "http://data-seed-prebsc-1-s2.binance.org:8545/",
    "http://data-seed-prebsc-2-s2.binance.org:8545/",
    "https://data-seed-prebsc-1-s3.binance.org:8545/",
    "https://data-seed-prebsc-2-s3.binance.org:8545/",
    "https://bsc-testnet.public.blastapi.io",
]

rootChainContract =  "0xc52b8eeB3d538523bfCA70839aC96af045A90301"

